# netlify.toml
# Configuración para despliegue en Netlify

[build]
  # Comando de construcción (ajustar según tu setup)
  command = "echo 'Generando configuración Firebase...' && node scripts/generate-config.js"
  
  # Directorio de publicación
  publish = "public"

[build.environment]
  NODE_ENV = "production"

# Configuración para rama de producción
[context.production]
  environment = { NODE_ENV = "production" }

# Configuración para rama de desarrollo
[context.branch-deploy]
  environment = { NODE_ENV = "development" }

# Headers de seguridad
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Redirecciones
[[redirects]]
  from = "/login"
  to = "/login.html"
  status = 200

[[redirects]]
  from = "/dashboard"
  to = "/dashboard-client.html"
  status = 200